name: Feature Request (Form)
description: Suggest a new feature for this SDK
title: "[Feature]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature. Your input helps us improve the SDK!

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: A clear and concise description of what the problem is.
      placeholder: "Example: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
      placeholder: "Example: It would be great if..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives/workarounds
      description: A clear and concise description of any alternative solutions or workarounds you've considered.
      placeholder: "Example: Currently I have to..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        #### Community guidelines
        All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

  - type: markdown
    attributes:
      value: |
        #### How to vote
        Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.