# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow performs a static analysis of your Kotlin source code using
# Detekt.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. On a weekly schedule
# 4. Manually, on demand, via the "workflow_dispatch" event
#
# The workflow should work with no modifications, but you might like to use a
# later version of the Detekt CLI by modifing the $DETEKT_RELEASE_TAG
# environment variable.
name: Vulnerability Scan with Detekt

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FUSIONAUTH_DOCKER_IMAGE_VERSION: 1.46.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    name: Detekt Scan

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      # Create and start FusionAuth containers used by E2E test
      - name: Start containers
        run: docker compose -f fusionauth/$FUSIONAUTH_DOCKER_IMAGE_VERSION/docker-compose.yml up -d

      # Setup and start Device Emulator used by E2E test
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Performs analysis using Detekt via Gradle and outputs a Sarif Report
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

        # Stop and remove FusionAuth containers to be used by E2E test
      - name: Stop containers
        if: always()
        run: docker compose -f fusionauth/$FUSIONAUTH_DOCKER_IMAGE_VERSION/docker-compose.yml down -v