# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow performs a Maven Pre-Release
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. On a weekly schedule
# 4. Manually, on demand, via the "workflow_dispatch" event
#

name: Maven Pre-Release

on:
  # Triggers the workflow on push request events but only for tag versions
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "scan"
  scan:
    name: Maven Pre-Release

    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Sets up JDK as a prerequisite to run Gradle
    - name: Setup Java
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'zulu'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    # Sets up Gradle as a prerequisite to run Maven Pre-Release
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        gradle-home-cache-cleanup: true

    # Performs a Local Maven Pre-Release
    - name: Run Maven Local Pre-Release
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
      run: ./gradlew publishReleasePublicationToMavenLocal
